<?php
/**
/* Intranet Notice
/*
/* Version 1.0
**/

function intranet_notice_init() {
  if(variable_get('intranet_notice_enabled', 0)) {

    // Add required JS from module dir
    $intranet_notice_path = drupal_get_path('module','intranet_notice');
    drupal_add_js($intranet_notice_path . '/inc/DD_belatedPNG_0.0.8a-min.js','module','header');
    drupal_add_js($intranet_notice_path . '/inc/jquery.meerkat.1.3.js','module','header');

    // Get user-selected server variables
    $server_url     = variable_get("intranet_notice_server_url", "");
    $json_element   = 'json.nodes[0].' . variable_get('intranet_notice_json_element', 'node_revisions_body');

    $meerkat = array(
        'close'             => (variable_get('intranet_notice_meerkat_close', '') != '') ? variable_get('intranet_notice_meerkat_close', '') : '',
        'dontShowAgain'     => (variable_get('intranet_notice_meerkat_dontShowAgain', 'none') != '') ? variable_get('intranet_notice_meerkat_dontShowAgain', 'none') : 'none',
        'cookieExpires'     => (variable_get('intranet_notice_meerkat_cookieExpires', 0) != 0) ? variable_get('intranet_notice_meerkat_cookieExpires', 0) : 0,
        'position'          => (variable_get('intranet_notice_meerkat_position', 'bottom') != '') ? variable_get('intranet_notice_meerkat_position', 'bottom') : 'bottom',
        'animationOut'      => (variable_get('intranet_notice_meerkat_animationOut', 'slide') != '') ? variable_get('intranet_notice_meerkat_animationOut', 'slide') : 'slide',
        'animationSpeed'    => (variable_get('intranet_notice_meerkat_animationSpeed', 'slow') != '') ? variable_get('intranet_notice_meerkat_animationSpeed', 'slow') : 'slow',
        'height'            => (variable_get('intranet_notice_meerkat_height', 'auto') != '') ? variable_get('intranet_notice_meerkat_height', 'auto') : 'auto',
        'background'        => (variable_get('intranet_notice_meerkat_background', 'none') != '') ? variable_get('intranet_notice_meerkat_background', 'none') : 'none'
    );

    // Build jQuery based off user-selected options
/*
    $js = '
        function bannerSlide() {
            jQuery("#ie6-content-container").each(function() {
                $(this).replaceWith(this.childNodes);
                jQuery("html").css({"overflow-y":"auto"});
            });
            $("#notice").slideDown("slow");
        };
*/
    $js = '
        function bannerSlide() {
            $("#notice").slideDown("slow");
	    $("#meerkat-transparent").remove();
        };

		function readCookie(name) {
			var nameEQ = name + "=";
			var ca = document.cookie.split(\';\');
			for(var i=0;i < ca.length;i++) {
				var c = ca[i];
				while (c.charAt(0)===\' \') c = c.substring(1,c.length);
				if (c.indexOf(nameEQ) === 0) return c.substring(nameEQ.length,c.length);
			}
			return null;
		}

        $(document).ready(function() {
            DD_belatedPNG.fix(".close-meerkat");
            $("body").append("<div id=\"meerkat\" style=\"display:none\"></div>");
            $.getJSON("' . $server_url . '", function(json) {
                $("#meerkat").html(' . $json_element . '+ "<a class=\"close-meerkat\" style=\"cursor: pointer;\"></a>");
                $("body").prepend("<div id=\"notice\" style=\"display:none\">" + ' . $json_element . ' + "</div>");

                var json_pass = new Array();
                $.each(json.nodes[0], function(i, val) {
                    if (val == "*") {
                        json_pass[i] = "";
		    } else {
                        json_pass[i] = val;
                    }
                });
    ';

    if(variable_get('intranet_notice_override', 0)) {
        $js .= '
                $("#meerkat").meerkat({
                    close: "' . $meerkat["close"] . '",
                    dontShowAgain: "' . $meerkat["dontShowAgain"] . '",
                    cookieExpires: "' . $meerkat["cookieExpires"] . '",
                    position: "' . $meerkat["position"] . '",
                    animationOut: "' . $meerkat["animationOut"] . '",
                    animationSpeed: ' . $meerkat["animationSpeed"] . ',
                    height: "' . $meerkat["height"] . '",
                    background: "' . $meerkat["background"] . '"
                });
        ';
    } else {
        $js .= '
                $("#meerkat").meerkat({
                    close: json_pass[\'node_data_field_close_field_close\'],
                    dontShowAgain: json_pass[\'node_data_field_close_field_dontshowagain\'],
                    cookieExpires: json_pass[\'node_data_field_close_field_cookieexpires\'],
                    position: json_pass[\'node_data_field_close_field_position\'],
                    animationOut: json_pass[\'node_data_field_close_field_animationout\'],
                    animationSpeed: parseFloat(json_pass[\'node_data_field_close_field_animationspeed\']),
                    height: json_pass[\'node_data_field_close_field_height\'],
                    background: json_pass[\'node_data_field_close_field_background\']
                });
        ';
    }

    $js .= '
                if(readCookie("meerkat") != "dontshow"){
                    $("' . $meerkat["close"] . '").click(function() {
			$("#meerkat-transparent").fadeOut("slow");
                        setTimeout("bannerSlide()", ' . $meerkat["animationSpeed"] . ');
                    });
                } else {
                    $("#notice").show();
                }
            });


        });
    ';

    // Add JS/CSS to page
    drupal_add_js($js,'inline','header');
    drupal_add_css($intranet_notice_path . '/inc/alerts.css');
  }
}

function intranet_notice_perm() {
  //return array with permissions for this module
  return array('intranet notice');
}

function intranet_notice_menu() {
  //build menu items and their permissions
  $items['admin/settings/intranet_notice'] = array(
    'title' => 'Intranet Notice',
    'description' => 'Administer Intranet Notice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_intranet_notice'),
    'access arguments' => array('intranet notice'),
  );

  return $items;
}

function _intranet_notice() {
  $form['intranet_notice'] = array(
    '#type' => 'fieldset',
    '#title' => t('Intranet Notice Settings'),
    );

  $form['intranet_notice']['intranet_notice_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enabled'),
    '#default_value' => variable_get('intranet_notice_enabled', 0),
    );

  $form['intranet_notice']['intranet_notice_override'] = array(
    '#type' => 'checkbox',
    '#title' => t('Override'),
    '#default_value' => variable_get('intranet_notice_override', 0),
    );

  $form['intranet_notice']['intranet_notice_server_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Server URL'),
    '#default_value' => variable_get('intranet_notice_server_url', ''),
    '#description' => t("URL for JSON string."),
    );

  $form['intranet_notice']['intranet_notice_json_element'] = array(
    '#type' => 'textfield',
    '#title' => t('JSON Element'),
    '#default_value' => variable_get('intranet_notice_json_element', 'node_revisions_body'),
    '#description' => t("Which JSON Element to display."),
    );

  $form['intranet_notice_meerkat'] = array(
    '#type' => 'fieldset',
    '#title' => t('Meerkat Settings'),
    );

  $form['intranet_notice_meerkat']['intranet_notice_meerkat_close'] = array(
    '#type' => 'textfield',
    '#title' => t('Close Selector'),
    '#default_value' => variable_get('intranet_notice_meerkat_close', ''),
    '#description' => t("When a user clicks on the selector you have set as your close option, Meerkat will close until it's reloaded again (defaults to 'none')."),
    );

  $form['intranet_notice_meerkat']['intranet_notice_meerkat_dontShowAgain'] = array(
    '#type' => 'textfield',
    '#title' => t('Dont Show Again'),
    '#default_value' => variable_get('intranet_notice_meerkat_dontShowAgain', 'none'),
    '#description' => t("When a user clicks on the selector you have set as your dontShow option, Meerkat will close and not show again until the browser session has ended (the user's browser has been restarted) or for a specific amount of days, depending on the dontShowExpire setting (defaults to 'none')."),
    );

  $form['intranet_notice_meerkat']['intranet_notice_meerkat_cookieExpires'] = array(
    '#type' => 'textfield',
    '#title' => t('Cookie Expire Time'),
    '#default_value' => variable_get('intranet_notice_meerkat_cookieExpires', 0),
    '#description' => t("If you set the cookieExpires option, you have the option of setting the length of time Meerkat will not show to that user for. Enter time in reference to days (defaults to 0)."),
    );

  $position = drupal_map_assoc(array('top','bottom'));
  $form['intranet_notice_meerkat']['intranet_notice_meerkat_position'] = array(
    '#type' => 'select',
    '#title' => t('Meerkat Position'),
    '#default_value' => variable_get('intranet_notice_meerkat_position', 'bottom'),
    '#options' => $position,
    '#description' => t("Location in browser that Meerkat will appear (defaults to 'bottom')."),
    );

  $animation = drupal_map_assoc(array('slide','fade'));
  $form['intranet_notice_meerkat']['intranet_notice_meerkat_animationOut'] = array(
    '#type' => 'select',
    '#title' => t('Animation'),
    '#default_value' => variable_get('intranet_notice_meerkat_animationOut', 'slide'),
    '#options' => $animation,
    '#description' => t("Method in which Meerkat will appear (defaults to 'slide')."),
    );

  $form['intranet_notice_meerkat']['intranet_notice_meerkat_animationSpeed'] = array(
    '#type' => 'textfield',
    '#title' => t('Animation Speed'),
    '#default_value' => variable_get('intranet_notice_meerkat_animationSpeed', 'slow'),
    '#description' => t("The animationSpeed option accepts the following values: ('slow', 'normal', or 'fast') or the number of milliseconds to run the animation (defaults to 'slow')."),
    );

  $form['intranet_notice_meerkat']['intranet_notice_meerkat_height'] = array(
    '#type' => 'textfield',
    '#title' => t('Height'),
    '#default_value' => variable_get('intranet_notice_meerkat_height', 'auto'),
    '#description' => t("The height option accepts all CSS height property values (px, em, %, auto, etc) (defaults to 'auto')."),
    );

  $form['intranet_notice_meerkat']['intranet_notice_meerkat_background'] = array(
    '#type' => 'textfield',
    '#title' => t('Background'),
    '#default_value' => variable_get('intranet_notice_meerkat_background', 'none'),
    '#description' => t("The background option accepts CSS background (shorthand) property values (defaults to 'none')."),
    );

  return system_settings_form($form);
}
